name: OWASP ZAP Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Start OWASP ZAP
        run: |
          # Pull the latest OWASP ZAP image
          docker pull owasp/zap

          # Run OWASP ZAP in daemon mode
          docker run -u zap -p 8080:8080 -d owasp/zap zap.sh -daemon -port 8080 -host 0.0.0.0
          sleep 10  # Esperar a que ZAP esté listo para recibir peticiones

          # Ejecutar los escaneos
          curl "http://localhos



