name: OWASP ZAP Security Scan

on:
  push:
    branches:
      - main

jobs:
  security_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Run OWASP ZAP
        run: |
          docker run -u zap -p 8080:8080 -d owasp/zap2docker-stable zap.sh -daemon -port 8080 -host 0.0.0.0
          sleep 10
          curl "http://localhost:8080/JSON/spider/action/scan/?url=http://your-app-url.com"
          curl "http://localhost:8080/JSON/ascan/action/scan/?url=http://your-app-url.com"
          curl "http://localhost:8080/OTHER/core/other/htmlreport/" > zap_report.html

      - name: Upload ZAP report
        uses: actions/upload-artifact@v2
        with:
          name: zap-report
          path: zap_report.html
