name: OWASP ZAP Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io

      - name: Run OWASP ZAP
        run: |
          docker pull owasp/zap2docker-weekly
          docker run -u zap -p 8080:8080 -d owasp/zap2docker-weekly zap.sh -daemon -port 8080 -host 0.0.0.0
          sleep 10
          curl "http://localhost:8080/JSON/spider/action/scan/?url=http://tu-app-url.com"
          curl "http://localhost:8080/JSON/ascan/action/scan/?url=http://tu-app-url.com"
          curl "http://localhost:8080/OTHER/core/other/htmlreport/" > zap_report.html

      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          name: zap-report
          path: zap_report.html



