name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  REPOSITORY_NAME: analistait16
  IMAGE_NAME: ats-rctl-cn-micro-root

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4.1.1

      - name: Calculate variables
        run: |
          echo "DATE=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV  
          echo "COMMIT_HASH=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Run Container lint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: src/main/docker/Dockerfile.native-micro
        continue-on-error: true

      - uses: pnpm/action-setup@v2
        with:
          version: 8.15.6
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - run: pnpm install

      - name: Update Pull Request
        uses: actions/github-script@v6
        if: github.event_name == 'pull_request'
        with:
          script: |
            const output = `
            #### Hadolint: \`${{ steps.hadolint.outcome }}\`
            \`\`\`
            ${process.env.HADOLINT_RESULTS}
            \`\`\`
            `;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.3.0

      - name: Get last commit
        run: echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Docker login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build and push container image
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          file: Dockerfile
          platforms: linux/arm64
          push: true
          tags: ${{ env.REPOSITORY_NAME }}/${{ env.IMAGE_NAME }}:${{ env.DATE }}-${{ env.COMMIT_HASH }}

      - name: Process Environment variables
        run: |
          echo "" >> ..DATA..
        shell: bash

      - name: Archive info artifacts
        uses: actions/upload-artifact@v4.3.1
        with:
          name: IMAGE_NAME-${{env.IMAGE_NAME}}
          path: |
            ..DATA..

      - name: Archive info artifacts
        uses: actions/upload-artifact@v4.3.1
        with:
          name: IMAGE_TAG-${{env.DATE}}-${{ env.IMAGE_TAG }}
          path: |
            ..DATA..
