name: OWASP ZAP Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run OWASP ZAP
        run: |
          docker pull owasp/dependency-check
          docker run -d --name zap -u zap -p 8080:8080 owasp/dependency-check zap.sh -daemon -host 0.0.0.0 -port 8080
          sleep 15  # Esperar a que ZAP esté listo

      - name: Run OWASP ZAP Spider Scan
        run: |
          curl "http://localhost:8080/JSON/spider/action/scan/?url=http://tu-app-url.com"
          curl "http://localhost:8080/JSON/ascan/action/scan/?url=http://tu-app-url.com"

      - name: Generate OWASP ZAP Report
        run: |
          curl "http://localhost:8080/OTHER/core/other/htmlreport/" > zap_report.html

      - name: Upload ZAP report
        uses: actions/upload-artifact@v3
        with:
          name: zap-report
          path: zap_report.html
